var searchData=
[
  ['postgresqltestcontainerconfiguration_0',['PostgreSqlTestcontainerConfiguration',['../class_dot_net_1_1_testcontainers_1_1_configurations_1_1_postgre_sql_testcontainer_configuration.html#a85e5fa7fee2203a6d7d433f93e56d3c4',1,'DotNet.Testcontainers.Configurations.PostgreSqlTestcontainerConfiguration.PostgreSqlTestcontainerConfiguration()'],['../class_dot_net_1_1_testcontainers_1_1_configurations_1_1_postgre_sql_testcontainer_configuration.html#a6ca985ea3edf7e6009ccf0843d151146',1,'DotNet.Testcontainers.Configurations.PostgreSqlTestcontainerConfiguration.PostgreSqlTestcontainerConfiguration(string image)']]]
];
